[package]
name = "discovery_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.37", features = ["cmake-build"] }
log = "0.4.20"
tokio = { version = "1", features = ["full"] }