---
version: '2'
services:
  arch-integ-kafka-ui:
    container_name: arch-integ-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
  arch-integ-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: arch-integ-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  arch-integ-broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: arch-integ-broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - arch-integ-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'arch-integ-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://arch-integ-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  arch-integ-dispatch-mqtt:
    image: eclipse-mosquitto:2.0.15
    hostname: mqtt
    ports: 
    - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
  arch-integ-agent-bridge:
    build: ./
    env_file: .env.bridge
    ports: 
    - "8083:8083"
  arch-integ-nodeagentsim:
    image: nodeagentsim:latest
    build: ../integration-tests/
    depends_on:
      - arch-integ-dispatch-mqtt
      - arch-integ-agent-bridge
    environment:
      - TEST_MQTT_HOST=arch-integ-dispatch-mqtt
    command: sh /tests/agent.sh

  arch-integ-bridgeconfig:
    image: bridgeconfig:latest
    build: ./config/
    depends_on:
      - arch-integ-agent-bridge
    environment:
      - TEST_BRIDGE_HOST=arch-integ-agent-bridge