name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./node_agent
    
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Start MQTT
      run: docker compose up -d
    - name: Run tests
      run: cargo test --verbose
